name: Security Scan and Fix

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security_scan:
    name: Security Scan and Fix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run npm audit for Security Issues
        id: npm-audit
        continue-on-error: true
        run: npm audit --json > npm-audit-results.json || true

      - name: Fix Security Issues Automatically
        run: npm audit fix || true

      - name: Check if Security Issues are Resolved
        id: audit-check
        run: |
          npm audit --json > post-audit-results.json || true
          ISSUES=$(jq '.metadata.vulnerabilities.total' post-audit-results.json)
          if [ "$ISSUES" -gt 0 ]; then
            echo "Security issues still exist!"
            exit 1
          else
            echo "No security issues found."
          fi

      - name: Set up Trivy (Docker Security Scan)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          trivy --version

      - name: Run Trivy Scan on Dockerfile
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      - name: Run Docker Image Scan
        run: |
          docker build -t my-app .
          trivy image --exit-code 1 --severity HIGH,CRITICAL my-app

